version: "3.8"

services:
  frontend:
    build: .
    restart: unless-stopped
    ports:
      - "8001:5173"
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - app-network

volumes:
  frontend_node_modules:

networks:
  app-network:
    driver: bridge