---
- name: Update apt packages
  apt:
    update_cache: yes
  tags: docker-compose

- name: Install Docker Compose plugin
  apt:
    name: docker-compose-plugin
    state: present
  tags: docker-compose

- name: Verify Docker Compose installation
  command: docker compose version
  register: docker_compose_version
  tags: docker-compose

- name: Display Docker Compose version
  debug:
    msg: "Installed Docker Compose version: {{ docker_compose_version.stdout }}"
  tags: docker-compose