name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > private_key.ppk
          chmod 600 private_key.ppk

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.ppk ubuntu@${{ secrets.AWS_EC2_IP }} << EOF
            set -e
            cd ~

            if [ -d "santhakumar_portfolio" ] && [ ! -d "santhakumar_portfolio/.git" ]; then
              rm -rf santhakumar_portfolio
            fi

            if [ ! -d "santhakumar_portfolio" ]; then
              git clone https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com/Santhakumar17/Portfolio-SanthaKumar.git santhakumar_portfolio
            fi

            cd santhakumar_portfolio
            cd application_code
            git pull https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com/Santhakumar17/Portfolio-SanthaKumar.git main

            sudo docker compose down || true
            sudo docker compose up --build -d
            sudo systemctl restart nginx || echo "⚠️ NGINX restart failed"
          EOF
